# Generated by Django 4.2.5 on 2023-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.CharField(default='https://www.youtube.com/', max_length=255),
        ),
    ]
