# Generated by Django 4.2.5 on 2023-09-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtuber_camera_type_alter_youtuber_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='banner',
            field=models.ImageField(blank=True, upload_to='media/ytubers/%Y/%m/'),
        ),
    ]
